apiVersion: v1
kind: Secret
metadata:
    name: synology-snmp-credentials
    namespace: monitoring
stringData:
    SNMP_COMMUNITY: ENC[AES256_GCM,data:1Pkpl4o2G4Q0zJWA+BYuJo+fTuqym1PJU+EQ7GmN32RWqu/nT9Ee3w==,iv:FK/iO7EpJimIyboFClTHKCfKwd0xTmbz6hoTkWBB0wQ=,tag:XnOrkr6Eh+4K2C+Ac6SXKQ==,type:str]
sops:
    age:
        - recipient: age1xuyqesapjwt8fhejc8cmtf2d2nwkmf2mqj0h4u0nke48lflc84mq9jsfs4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNmhnRWNhcWVVcHBDTWc3
            Mi9JaVZjT1I4OU0xWE5WV0dMdTkvbnhTcUU0ClNReHNBRk9yS3QwMFVNcDRjYUs0
            cks4bFJuTzdCMXhhWFpLVndYK2Y1QlkKLS0tIFllbC9OYm1FMHVRZXpLbjU0RVhG
            UGd3YmNveEVFWjhCL29IQk5MV00vcU0KmwO2dHT97623Ndt/Jiuhb07nZBL3v6Jz
            L0OYfX4GL9xEa5P3yJz7G3+fAFe/7c4FsMihI4eIb3ivil9FxXfkbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T20:00:55Z"
    mac: ENC[AES256_GCM,data:H4f+5zrsGfsc7+pboxzTXmGfd9nYJnPxvPKR2YfsiCSWwbxASNaL6LiHCKoA2qND5QHWUIHb1WfX5t8r74IFKcLl0k06pnqbeNByh1Uv5h42H1ohyqwVA5RvhM1bTNoI6NmgqFOsHCNNb8DBo7SaJPQGeZSImxaOptoCLDF5Lzk=,iv:KkHoGaxbg0vTJdVI1L1oM7SJz/Tv26Wdz6o+BBWNcbU=,tag:vvOotP1xyVz4uWydx5dfDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
