apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:IbXGg1lQenWeCbT3TH9JZbF0sbM24uqQ160C/gx6GB5x3j5zQJm/UmL5dWaXCgVQu4B+nqb54W/VcKWU7Zk+trOYv6R3hwJs5ii3ycKhsb4=,iv:2JiyHzMOAR4OIg3/VjLb4ssiTclMc8QKADFeYl0tsd4=,tag:z4tR4wYSZpuEjyCyiC4Gtg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: traefik-vercel-api-token
    namespace: kube-system
sops:
    age:
        - recipient: age1xuyqesapjwt8fhejc8cmtf2d2nwkmf2mqj0h4u0nke48lflc84mq9jsfs4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKV3RhQlMzOFdKeGdxRXNB
            RHZycmQ0NEhHY1oyeWNvRHduZ24vSThQTndRCjZJTkg2bVNYNkpkTUhHTkc1cVVs
            dWNaWUNNRFNDVEtkbmcramtsZVdkdDAKLS0tIFdSNFVGS3l1MkNGeVF1OEkvWjJa
            eXp2VmFTNW1DNytFM2Z4VFdFSzdHUncKcPanaUlL5J7GG/cUyRJf66XPlKyNYtuh
            toeXnM4x3IG4uMx2H0j3ylNso/zKOYc2m4toXgByPFk2bW1TknZS0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-23T11:17:45Z"
    mac: ENC[AES256_GCM,data:bZmR0dlci3SMiJ1UYZUoyv5mrUSseE7/TZEHcdCVdbZfZPbIlKUqqEt4K7dSqVDrobUGnHV87SLrqA4+5Y7pwvltUDk+0jx7r/6m0X9TONGBLjDoCmhTaN9HUr7eLZ5fZifaSZAXIPTgS7qK4NAyxi5bPwcho33Jn2buDZQ4BBs=,iv:9htZj1pdgWi47KkthXlTdwDJHSkxT+ZNu9DDgwyuh1A=,tag:v921ZYHhY9OjuUHroO/6ZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
